### ISSUE TITLE
[1.7.10] Scrolls are WAY too common in chests

### ISSUE THREAD

**Issue by Shahelion** [Epoxide-MC/EnchantingPlus#107]
No config for this, either.

**Comment by Darkhax** [comment]
Thanks for the feedback. Even at the time of this issue being opened, 1.7.10 was extremely old and not being supported. Releases for 1.8+ had config options for scrolls, and in the current 1.12.2 version scrolls are not found in chests at all. For more info on the current 1.12.2 rewrite, check out the active repo [here](https://github.com/Darkhax-Minecraft/Enchanting-Plus)
