### ISSUE TITLE
CTD (Memory Leak)

### ISSUE THREAD

**Issue by Lithorn** [Epoxide-MC/EnchantingPlus#108]
Enchanting any pick with Fortune and "Heat", and mining certain blocks (Like Gregtech Black Granite) causes the client to expend all memory and close

**Comment by Darkhax** [comment]
This issue tracker is up for legacy reasons. Please see [this](https://github.com/Darkhax-Minecraft/Enchanting-Plus/issues) page for the real one!

As for your issue, this seems like an issue with whichever mod adds the heat enchantment. If heat is not meant to be applied with fortune they need to set that limitation in their code.

**Comment by Lithorn** [comment]
Yeah I closed this when I saw I had the wrong github, Thankyou anyway! It shouldnt work with fortune I don't think.
