### ISSUE TITLE
Enchanting scrolls disconnect user using scroll

### ISSUE THREAD

**Issue by Klackos** [Epoxide-MC/EnchantingPlus#109]
Whenever we try to hold use on a scroll, it just immediately disconnects the person attempting to read the scroll. It says "connection lost" "Internal Server Error."

That's it.

Will attempt to reinstall the mod to see if it was a problem with installation, before doing a bit of code diving, any advice outside that would be appreciated.

~Klackos

**Comment by Klackos** [comment]
Works in single player just fine, but not on our server, could it be that it's not designed to work on a server?

**Comment by Darkhax** [comment]
Thanks for opening your issue. This is an archived version of the repo. Bugs should be reported [here](https://github.com/Darkhax-Minecraft/Enchanting-Plus). The mod is currently going through a thorough rewrite, and this issue is likely no longer relevant.
